# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2a1977fdd003bb3f632f974ecc9e85c4db2a4918e2abec294399678b974a7b231af99145afee7f8d2f195fb73f6292786efe3448ca46dbd27dcc0abf1427439

test:
  secret_key_base: 47ae997020a90dd4ca1486c90c586af552f1ddb66b9ba13d9ba1703c257abff612ab738793ecf2c18d4facde34298a4d59f2f5ba1b93f8503aefdda62f82c328

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
